name: Funny Action

on: [push]

jobs:
  funny_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get a random joke from the jokeapi
        id: joke
        run: |
          joke=$(curl -s https://v2.jokeapi.dev/joke/Any?type=single | jq -r '.joke')
          echo "Joke: $joke"
          echo "::set-output name=joke::$joke"

      - name: Check if joke contains the word 'cat'
        run: |
          if [[ "${{ steps.joke.outputs.joke }}" == *"cat"* ]]; then
            echo "Found a funny joke about a cat! Proceeding..."
          else
            echo "No cat joke found. Failing the action..."
            exit 1
        continue-on-error: false
