name: Funny Action

on: [push]

jobs:
  funny_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get a random joke from the jokeapi
        id: joke
        run: |
          joke=$(curl -s https://v2.jokeapi.dev/joke/Any?type=single | jq -r '.joke')
          echo "Joke: $joke"
          echo "joke=$joke" >> $GITHUB_ENV  # Set the joke as an environment variable

      - name: Check if joke contains the word 'cat'
        run: |
          if [[ "$CAT_JOKE" == *"cat"* ]]; then
            echo "Found a funny joke about a cat! Proceeding..."
          else
            echo "No cat joke found. Failing the action..."
            exit 1
        env:
          CAT_JOKE: ${{ env.joke }}  # Use the joke stored in the environment variable
